name: "My Local Action"
description: "Una acción local de ejemplo"

inputs:
  message:
    description: "Pruebas"
    required: True
    default: "Hola"

runs:
  using: "composite"
  steps:
    - run: echo "Hola ${{ inputs.message }}"
      shell: bash