name: Test
on: 
  workflow_dispatch:
    inputs:
      test:
        description: "Prueba"
        required: true
        default: "Hola"

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Otorgar permisos de ejecución al script
        run: chmod +x script.sh
      - name: Ejecutar script
        run: ./script.sh
        
