name: Test Composite Action
on: push
jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: ls
        uses: ./.github/actions/my_actions
        with:
          message: "Rodrigo"
    services:
      mysql:
        image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
          