name: Test Composite Action
on: push
jobs:
  local-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: ls
        uses: ./.github/actions/my_actions