name: Test Composite Action
on: push
jobs:
  local-action:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: RR1
    
    steps:
      - name: step
        env:
          STEP_MY_VAR: RR2
        run: echo "Valor: ${{ env.MY_ENV_VAR }}"
        run: echo "Valor: ${{ env.STEP_MY_VAR }}"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: ls
        uses: ./.github/actions/my_actions
        with:
          message: "Rodrigoo"
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
      redis:
        image: redis:latest
        ports:
          - 6379:6379
          